export const personalInfo = {
  name: "Koceila Djaballah",
  title: "Full Stack Developer | AI Specialist | SaaS Solutions Architect",
  location: "Montreal, QC",
  email: "koceila.djaballah@gmail.com",
  phone: "+1 (438) 282-1633",
  github: "https://github.com/ITNKOC",
  linkedin: "https://linkedin.com/in/koceila-djaballah-295716221",
  bio: "Dev Full Stack passionné avec 1 an d'expérience en transformation digitale. Chez Di Menna Restaurant, j'ai mené la transformation tech complète : 2 apps web en prod (e-commerce + POS Lightspeed + plateforme marketing IA), infra cloud, et support client. Bref, du dev qui change la donne ! 💪",
};

export const experience = [
  {
    title: "Développeur Full Stack & Chargé TI",
    company: "Restaurant Di Menna",
    location: "Montreal, QC",
    period: "Nov. 2024 - Dec. 2025",
    duration: "1 an",
    description: [
      "🚀 Boss de la transformation digitale pendant 1 an : designé, codé et déployé 2 apps web en production",
      "💻 Créé une plateforme e-commerce full-stack (Next.js 15/React 19) avec intégration POS Lightspeed OAuth2, sync temps réel via webhooks, module RH & gestion multi-users",
      "🤖 Développé un SaaS Marketing IA : outil de transformation d'images alimentaires générant 4 versions pro avec Gemini 2.5 Flash + génération de contenu marketing automatisé",
      "☁️ Géré le DevOps complet : archi cloud (Vercel/Neon), CI/CD avec GitHub Actions, monitoring des performances",
    ],
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "PostgreSQL",
      "Prisma ORM",
      "Express.js",
      "Google Gemini API",
      "NextAuth",
      "Cloudinary CDN",
      "Tailwind CSS",
      "Docker",
    ],
  },
  {
    title: "Développeur Full Stack & IA (Stage de fin d'études)",
    company: "Plateforme SaaS de Gestion Hospitalière",
    location: "Montreal, QC",
    period: "Dec. 2024 - Apr. 2025",
    duration: "5 months",
    description: [
      "Collaborative development of medical SaaS platform with microservices architecture (Team of 4)",
      "Integrated fine-tuned LLM agents with RAG for contextual medical assistance and intelligent appointment scheduling",
      "Created deep learning models (PyTorch, OpenCV) for automatic pathology detection: tuberculosis and malaria",
      "Implemented secure EMR system: JWT authentication, data encryption, permissions management",
      "Applied Scrum methodology: sprint planning, user stories, daily stand-ups, retrospectives",
    ],
    tech: [
      "Python",
      "Flask/FastAPI",
      "React.js",
      "PostgreSQL",
      "Docker",
      "NLP",
      "OpenCV",
      "PyTorch",
      "LangChain",
      "Tailwind CSS",
    ],
  },
  {
    title: "Développeur Web Freelance",
    company: "Various Clients",
    location: "Montreal & Remote",
    period: "2021 - 2024",
    duration: "3 years",
    description: [
      "Designed and delivered complete websites (showcases, e-commerce) for SMEs and individuals",
      "Full-cycle autonomous project management: needs analysis, UX/UI design, development, testing, deployment, maintenance",
    ],
    tech: ["PHP", "JavaScript", "HTML/CSS", "MySQL", "WordPress"],
  },
];

export const projects = [
  {
    title: "DiMenna Express - E-commerce Platform",
    subtitle: "Plateforme E-commerce Full-Stack avec POS Integration",
    description:
      "Plateforme e-commerce complète avec intégration POS Lightspeed en temps réel, gestion RH et module multi-utilisateurs. Code privé - En production ! 🚀",
    image: "/images/dimenna-ecommerce.jpg",
    features: [
      "Intégration OAuth2 avec Lightspeed POS pour sync temps réel des produits et inventaire",
      "Système de webhooks pour mises à jour automatiques du catalogue",
      "Module RH complet avec gestion des employés et permissions",
      "Architecture multi-utilisateurs sécurisée avec NextAuth",
      "Dashboard admin avancé pour gestion des commandes et analytics",
      "Optimisation des performances et déploiement cloud (Vercel + Neon)",
    ],
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "PostgreSQL",
      "Prisma ORM",
      "NextAuth",
      "Lightspeed API",
      "Tailwind CSS",
      "Vercel",
    ],
    github: "#",
    demo: "https://dimenna-express-web-app-v2.vercel.app/",
    year: "2024",
    featured: true,
  },
  {
    title: "DiMenna.com - Site Vitrine",
    subtitle: "Site Web Vitrine Restaurant",
    description:
      "Site vitrine élégant et responsive pour Restaurant Di Menna. Design moderne avec menu interactif, galerie photos et intégration Google Maps. En production ! 🍝",
    image: "/images/dimenna-vitrine.jpg",
    features: [
      "Design responsive et moderne adapté à tous les appareils",
      "Menu interactif avec catégories et descriptions détaillées",
      "Galerie photos professionnelle du restaurant et des plats",
      "Intégration Google Maps et informations de contact",
      "Performance optimisée et SEO",
    ],
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Vercel",
    ],
    github: "#",
    demo: "https://dimenna.com",
    year: "2024",
    featured: true,
  },
  {
    title: "Product Scorecard",
    subtitle: "SaaS d'Analyse de Viabilité E-commerce",
    description:
      "Plateforme intelligente pour entrepreneurs : valide la viabilité commerciale de tes produits avant d'investir ! 💡",
    image: "/images/product-scorecard.jpg",
    features: [
      "Wizard intelligent en 8 étapes avec collecte de données structurée et auto-save",
      "Coach IA contextuel via Google Gemini API qui s'adapte à tes données produit",
      "Algorithme de scoring propriétaire (0-100) basé sur 8 critères pondérés",
      "Rapports stratégiques automatisés : analyses SWOT, personas clients, recommandations marketing",
    ],
    tech: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "Prisma ORM",
      "Zustand",
      "Gemini 1.5 Flash",
      "Tailwind CSS",
      "Docker",
    ],
    github: "#",
    demo: "https://product-scorecard-yanis.vercel.app/",
    year: "2024",
    featured: true,
  },
  {
    title: "Image4Marketing",
    subtitle: "SaaS Marketing Visuel par IA 🎨",
    description:
      "App SaaS complète qui transforme tes images alimentaires en contenu marketing pro via IA générative. Utilisée en production par Restaurant Di Menna ! 🔥",
    image: "/images/image4marketing.jpg",
    features: [
      "Workflow en 5 étapes : Upload → Génération de 4 variations optimisées → Modifs par chat IA → Export avec captions",
      "Features avancées : auth NextAuth v5, galerie utilisateur, partage public, rate limiting",
      "Intégration Gemini Vision pour analyse visuelle auto et génération de contenu marketing",
      "Variations pro : e-commerce, livraison, réseaux sociaux, bannières hero",
    ],
    tech: [
      "Next.js 14",
      "React 18",
      "TypeScript",
      "PostgreSQL",
      "Prisma",
      "NextAuth v5",
      "Gemini 2.5 Flash Image",
      "Cloudinary CDN",
      "Sharp",
      "Framer Motion",
    ],
    github: "#",
    demo: "https://image4marketing.vercel.app/",
    year: "2024",
    featured: true,
  },
  {
    title: "Hospital Management Platform",
    subtitle: "Intelligent Medical SaaS",
    description:
      "Advanced medical SaaS platform with microservices architecture for modern hospital management. Academic final project with team of 4.",
    image: "/images/hospital.jpg",
    features: [
      "Fine-tuned LLM agents with RAG for contextual medical assistance",
      "Deep Learning models for pathology detection (tuberculosis, malaria)",
      "Secure EMR system with JWT authentication and data encryption",
      "Scrum methodology applied throughout development",
    ],
    tech: [
      "Python",
      "Flask/FastAPI",
      "React.js",
      "PostgreSQL",
      "Docker",
      "NLP",
      "OpenCV",
      "PyTorch",
      "LangChain",
    ],
    github: "#",
    demo: "#",
    year: "2024-2025",
    featured: true,
  },
  {
    title: "CBIR System",
    subtitle: "Content-Based Image Retrieval",
    description:
      "Advanced image search engine based on visual similarity using computer vision techniques.",
    image: "/images/cbir.jpg",
    features: [
      "Visual feature extraction via GLCM (texture) and BiT descriptors",
      "4 distance metrics implementation for optimal relevance",
      "Interactive Streamlit interface",
    ],
    tech: ["Python", "OpenCV", "scikit-image", "NumPy", "Streamlit"],
    github: "#",
    demo: "#",
    year: "2024",
  },
  {
    title: "E-commerce Platforms",
    subtitle: "Multi-Technology Full Stack Projects",
    description:
      "Various e-commerce platforms built with different technology stacks.",
    image: "/images/ecommerce.jpg",
    features: [
      "PHP E-commerce: Clothing store with MVC architecture",
      "MERN E-commerce: Perfume platform with RESTful API and Redux",
      "Complete catalog management, secure payment systems",
    ],
    tech: ["PHP", "MySQL", "MongoDB", "Express.js", "React", "Node.js"],
    github: "#",
    demo: "#",
    year: "2023",
  },
  {
    title: "Uber Clone",
    subtitle: "Mobile Transportation App",
    description:
      "Complete transportation mobile app with separate client/driver interfaces.",
    image: "/images/uber-clone.jpg",
    features: [
      "Real-time geolocation via Google Maps API",
      "Firebase authentication and integrated payment",
      "Scalable serverless backend architecture",
    ],
    tech: ["Flutter", "Firebase", "Google Maps API"],
    github: "#",
    demo: "#",
    year: "2023",
  },
];

export const skills = {
  languages: [
    { name: "Python", level: 95, category: "expert" },
    { name: "JavaScript", level: 95, category: "expert" },
    { name: "TypeScript", level: 80, category: "expert" },
    { name: "Java", level: 90, category: "advanced" },
    { name: "C/C++", level: 65, category: "advanced" },
    { name: "C#", level: 75, category: "advanced" },
    { name: "PHP", level: 80, category: "advanced" },
    { name: "Dart", level: 50, category: "base" },
    { name: "SQL", level: 95, category: "advanced" },
  ],
  frontend: [
    { name: "Next.js", level: 95 },
    { name: "React", level: 95 },
    { name: "Tailwind CSS", level: 90 },
    { name: "Flutter", level: 50 },
    { name: "Framer Motion", level: 85 },
  ],
  backend: [
    { name: "Node.js", level: 90 },
    { name: "Express.js", level: 90 },
    { name: "Flask", level: 85 },
    { name: "FastAPI", level: 85 },
  ],
  ai: [
    { name: "PyTorch", level: 85 },
    { name: "LangChain", level: 90 },
    { name: "HuggingFace", level: 80 },
    { name: "Google Gemini API", level: 95 },
    { name: "OpenCV", level: 85 },
    { name: "RAG", level: 90 },
    { name: "NLP", level: 85 },
  ],
  databases: [
    { name: "PostgreSQL", level: 90 },
    { name: "MongoDB", level: 85 },
    { name: "MySQL", level: 85 },
    { name: "Prisma ORM", level: 95 },
  ],
  devops: [
    { name: "Docker", level: 85 },
    { name: "Git/GitHub", level: 95 },
    { name: "CI/CD", level: 85 },
    { name: "Vercel", level: 90 },
    { name: "AWS", level: 75 },
    { name: "Azure", level: 75 },
  ],
};

export const education = [
  {
    degree: "DEC in Web Programming and Artificial Intelligence",
    school: "Institut Teccart",
    location: "Montreal, QC",
    period: "Jan 2023 - Apr 2025",
    description:
      "Intensive training in AI-integrated application development and modern web technologies. Practical projects: computer vision, SaaS platforms, deep learning, Agile/Scrum methodologies.",
  },
  {
    degree: "Bachelor's Degree in Computer Science",
    school: "Université Abderrahmane Mira",
    location: "Béjaïa, Algeria",
    period: "2019 - Sept 2022",
    description:
      "Advanced algorithms, data structures, software engineering, databases, AI fundamentals. Official Quebec equivalence obtained (MIFI).",
  },
];

export const languages = [
  { language: "French", level: "Native", flag: "🇫🇷" },
  { language: "English", level: "Professional (B2)", flag: "🇬🇧" },
  { language: "Arabic", level: "Fluent", flag: "🇸🇦" },
  { language: "Kabyle", level: "Native", flag: "🗣️" },
  { language: "Spanish", level: "Basic (A2)", flag: "🇪🇸" },
];
